version: "3.7"

services:
  ferm:
    build: ./app/
    ports:
    - "4001:4001"
    links:
    - mongo
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - "./data:/data/db"

